"""empty message

Revision ID: 581eb6802523
Revises: 1b1f23ce9deb
Create Date: 2022-07-21 17:38:00.942961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581eb6802523'
down_revision = '1b1f23ce9deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('peoples_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['peoples_id'], ['peoples.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
