"""empty message

Revision ID: d42f2c607c89
Revises: ce1cdc4ba358
Create Date: 2022-07-25 15:21:19.521621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd42f2c607c89'
down_revision = 'ce1cdc4ba358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_peoples_ibfk_2', 'favorites_peoples', type_='foreignkey')
    op.drop_column('favorites_peoples', 'planets_id')
    op.drop_constraint('favorites_planets_ibfk_1', 'favorites_planets', type_='foreignkey')
    op.drop_column('favorites_planets', 'peoples_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites_planets', sa.Column('peoples_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorites_planets_ibfk_1', 'favorites_planets', 'peoples', ['peoples_id'], ['id'])
    op.add_column('favorites_peoples', sa.Column('planets_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorites_peoples_ibfk_2', 'favorites_peoples', 'planets', ['planets_id'], ['id'])
    # ### end Alembic commands ###
